version: "2"
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "3000:3000"
    depends_on: 
      - mongo  
    links:
      - mongo
  frontend:
    ports:
      - 8080:8080
    build:
      context: ../agiler-ui
      dockerfile: Dockerfile
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"