---
version: 2
jobs: 
 build: 
   machine:
      enable: true
   steps: 
     - checkout
     - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}z
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm run test
  deploy: 
    machine:
      enable: true
    steps:
      - name: do dir
      - command: ls -la

 workflows:
  version: 2
  build_and_test: 
    jobs: 
     - build 
     - deploy
